language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3"
install:
  - pip install --index-url 'https://:2020-06-27T23:45:03.457785Z@time-machines-pypi.sealsecurity.io/' .
script:
  - python -m unittest discover
